version: '2.2'
services:
  web:
    build:
      context: web
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./web:/app-src

  api:
    build:
      context: api
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    encrypted_env_file: deployment.env.encrypted
    command: sls offline start --host 0.0.0.0 --stage test --noEnvironment

  awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes_from:
      - web

  kiosk:
    build:
      context: kiosk
      dockerfile: docker/Dockerfile
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./kiosk:/app-src
      - /app-src/node_modules

  kiosk_deployment:
    image: codeship/aws-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes_from:
      - kiosk
