version: '2.2'
services:
  web:
    build:
      context: web
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./web:/app-src

  serverless:
    build:
      image: codeship/screendriver_serverless
      context: api
      dockerfile: docker/Dockerfile.serverless
    encrypted_env_file: deployment.env.encrypted
    cached: true
    default_cache_branch: "staging"

  api:
    build:
      context: api
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    encrypted_env_file: deployment.env.encrypted

  awsdeployment:
    image: codeship/aws-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes_from:
      - web

  kiosk:
    build:
      context: kiosk
      dockerfile: docker/Dockerfile
    encrypted_env_file: deployment.env.encrypted
    volumes:
      - ./kiosk:/app-src
      - /app-src/node_modules

  kiosk_deployment:
    image: codeship/aws-deployment
    encrypted_env_file: deployment.env.encrypted
    volumes_from:
      - kiosk
