version: '2.2'
services:

  build_web:
    env_file:
      - development.env
    build:
      context: web
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./web:/app-src
      - /app-src/node_modules

  deploy_web:
    env_file:
      - development.env
    build:
      context: web
      dockerfile: ./docker/Dockerfile.deploy
    volumes_from:
      - build_web

  deploy_shared_resources:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.deploy
      args:
        SERVICE: shared-resources-service
    volumes:
      - ./api/services/shared-resources-service/.serverless:/app-src/shared-resources-service/.serverless

  deploy_api:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.deploy
      args:
        SERVICE: content-management-service
    volumes:
      - ./api/services/content-management-service/.serverless:/app-src/content-management-service/.serverless

  deploy_auth_api:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.deploy
      args:
        SERVICE: auth-service
    volumes:
      - ./api/services/auth-service/.serverless:/app-src/auth-service/.serverless

  deploy_maintenance_api:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.deploy
      args:
        SERVICE: maintenance-service
    volumes:
      - ./api/services/maintenance-service/.serverless:/app-src/maintenance-service/.serverless

  api_create_user:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.create_user

  build_kiosk:
    env_file:
      - development.env
    build:
      context: kiosk
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./kiosk/dist:/app-src/dist
