version: '2.2'
services:
  web:
    build:
      context: web
      dockerfile: ./docker/Dockerfile.deps
    ports:
      - "4200:4200"
    command: npm start
  api:
    build:
      context: api
      dockerfile: ./docker/Dockerfile.deps
    #ports:
      #- "8000:8000"
    command: sls offline start --host 0.0.0.0 --stage test --noEnvironment
