version: '2.2'
services:

  api_test:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.startup
      args:
        SERVICE: content-management-service

  auth_api_test:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.startup
      args:
        SERVICE: auth-service

  maintenance_api_test:
    env_file:
      - development.env
    build:
      context: api
      dockerfile: ./docker/Dockerfile.startup
      args:
        SERVICE: maintenance-service
