service: screen-driver-shared

frameworkVersion: ">=1.24.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage, 'dev'}

custom:
  environment: ${file(./serverless/environment.yml)}
  cognitoResources: ${file(./serverless/cognito-resources.yml)}
  customizeCognitoMessagePermission: ${file(./serverless/customize_cognito_message_permission.yml)}
  resources: ${file(./serverless/resources.yml)}
  outputs: ${file(./serverless/outputs.yml)}

functions:
  customizeCognitoMessage:
    handler: src/message_customizer.handler
    environment: ${self:custom.environment.clientAppUrl}

resources:
  Resources: ${self:custom.resources}
  Outputs: ${self:custom.outputs}
