ApiTokenResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    ParentId: ${self:custom.rootUrlId}
    PathPart: token
    RestApiId: ${self:custom.restApiId}

ApiTokenRefreshResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    ParentId:
      Ref: ApiTokenResource
    PathPart: refresh
    RestApiId: ${self:custom.restApiId}

ApiTokenRefreshOptionsMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    MethodResponses: ${self:custom.optionsMethod.MethodResponses}
    Integration: ${self:custom.optionsMethod.Integration}
    ResourceId:
      Ref: ApiTokenRefreshResource
    RestApiId: ${self:custom.restApiId}

ApiTokenRefreshPostMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: POST
    ResourceId:
      Ref: ApiTokenRefreshResource
    RestApiId: ${self:custom.restApiId}
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri:
        Fn::Join:
          - ''
          - - ${self:custom.baseLambdaUri}
            - Fn::GetAtt:
              - RefreshUnderscoretokenLambdaFunction
              - Arn
            - '/invocations'

RefreshTokenFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
      Fn::GetAtt:
        - RefreshUnderscoretokenLambdaFunction
        - Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: ${self:custom.restApiArn}