'use strict';

// tests for update_venue
// Generated by serverless-mocha-plugin
require('./test_provider_configurator').configure();
const DatabaseCleaner = require('./database_cleaner');

const mod = require('../venues/update.js');
const createFunction = require('../venues/create.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrappedUpdate = lambdaWrapper.wrap(mod, {handler: 'update'});
const wrappedCreate = lambdaWrapper.wrap(createFunction, {handler: 'create'});
const idLength = 36;

describe('update_venue', () => {
    before((done) => {
        DatabaseCleaner.cleanDatabase().then(() => done());
    });

    afterEach(done => {
        DatabaseCleaner.cleanDatabase().then(() => done());
    });

    it('Can update venue name', () => {
        let newVenue = {name: "Hakkasan"};
        let updatedVenue = {name: "Hakkasan LV", _rev: 0};

        return createUpdateAndTest(newVenue, updatedVenue, (body) => {
            expect(body).to.have.property("name").that.equal("Hakkasan LV");
        });
    });

    it('Can update venue content id', () => {
        let newVenue = {name: "Hakkasan"};
        let updatedVenue = {name: "Hakkasan", content_id: "710b962e-041c-11e1-9234-0123456789ab", _rev: 0};

        return createUpdateAndTest(newVenue, updatedVenue, (body) => {
            expect(body).to.have.property("content_id").that.equal("710b962e-041c-11e1-9234-0123456789ab");
        });
    });

    it('Can update venue screen groups names', () => {
        let newVenue = {name: "Hakkasan", screen_groups: [{name: "Touch"}, {name: "Deli"}]};
        let updatedVenue = {name: "Hakkasan", screen_groups: [{name: "Menu"}, {name: "Restaurant"}], _rev: 0};

        return createUpdateAndTest(newVenue, updatedVenue, (body) => {
            expect(body.screen_groups[0]).to.have.property("name").that.equal("Menu");
            expect(body.screen_groups[1]).to.have.property("name").that.equal("Restaurant");
        });
    });

    it('Add screen group to existing venue, and id will be generated automatically', () => {
        let newVenue = {name: "Hakkasan", screen_groups: [{name: "Touch"}]};
        let updatedVenue = {name: "Hakkasan", screen_groups: [{name: "Touch"}, {name: "Deli"}], _rev: 0};

        return createUpdateAndTest(newVenue, updatedVenue, (body) => {
            expect(body.screen_groups[0]).to.have.property("name").that.equal("Touch");
            expect(body.screen_groups[1]).to.have.property("name").that.equal("Deli");
            expect(body.screen_groups[1]).to.have.property("id").with.lengthOf(idLength);
        });
    });

    it('Add screen to existing screen group, and id will be generated automatically', () => {
        let newVenue = {name: "Hakkasan", screen_groups: [{name: "Touch", screens: [{name: "A"}]}]};
        let updatedVenue = {
            name: "Hakkasan",
            screen_groups: [{name: "Touch", screens: [{name: "A"}, {name: "B"}]}],
            _rev: 0
        };

        return createUpdateAndTest(newVenue, updatedVenue, (body) => {
            expect(body.screen_groups[0].screens[0]).to.have.property("name").that.equal("A");
            expect(body.screen_groups[0].screens[1]).to.have.property("name").that.equal("B");
            expect(body.screen_groups[0].screens[1]).to.have.property("id").with.lengthOf(idLength);
        });
    });

    it('Couldn\'t change venue name to existing name', () => {
        let existingVenue = {name: "Hakkasan LV"};
        let newVenue = {name: "Hakkasan"};
        let updatedVenue = {name: "Hakkasan LV", _rev: 0};

        return createVenue(getParametersFor(existingVenue)).then((res) => {
            return createUpdateAndTest(newVenue, updatedVenue, (body, response) => {
                expect(response).to.have.property("statusCode").that.equal(500);
            })
        });
    });

});

function createVenue(params) {
    return wrappedCreate.run(params);
}

function createUpdateAndTest(newVenue, updatedVenue, expectations) {
    return createVenue(getParametersFor(newVenue))
        .then((response) => {
            return wrappedUpdate.run(getParametersFor(updatedVenue, response))
        }).then(response => {
            let body = JSON.parse(response.body);
            expectations(body, response);
        });
}

function getParametersFor(venue, response) {
    let params = {};
    if (response) {
        let responseBody = JSON.parse(response.body);
        let id = responseBody.id;
        responseBody.screen_groups.forEach(group => {
            _addId(venue, 'screen_groups', group);
            group.screens.forEach(screen => _addId(group, 'screens', screen))
        });
        params.pathParameters = {};
        params.pathParameters.id = id;
    }
    params.body = JSON.stringify(venue);
    return params;

    function _addId(sourceElement, sourceField, destinationElement) {
        destinationElement.id = sourceElement[sourceField].map(element => element.name == destinationElement.name)[0].id;
    }
}