CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ScreenDriverUserPool-${opt:stage, 'dev'}
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireUppercase: true
        RequireNumbers: true
        RequireSymbols: false
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: true
      InviteMessageTemplate:
        EmailSubject: "[ScreenDriver] Welcome to ScreenDriver"
        EmailMessage: "Your ID is {username} and temporary password is {####}."
    AliasAttributes:
      - email
    AutoVerifiedAttributes:
      - email
    EmailVerificationSubject: "[ScreenDriver] Your password reset verification code"
    EmailVerificationMessage: "You recently requested for resetting the password. Use the following code to verify your identity: {####}"
    LambdaConfig:
      CustomMessage:
        Fn::GetAtt:
          - CustomizeCognitoMessageLambdaFunction
          - Arn
    Schema:
      - Name: admin
        AttributeDataType: Boolean
        Mutable: true

CognitoAppClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ScreenDriverAppClient-${opt:stage, 'dev'}
    RefreshTokenValidity: 1
    UserPoolId:
      Ref: CognitoUserPool
