CustomizeCognitoMessagePermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName:
      Fn::GetAtt:
        - CustomizeCognitoMessageLambdaFunction
        - Arn
    Principal: cognito-idp.amazonaws.com
    SourceArn:
      Fn::GetAtt:
        - CognitoUserPool
        - Arn
