FROM screendriver_serverless

ARG SERVICE

WORKDIR ../app-src
RUN mkdir $SERVICE
RUN cp -r ../deps/node_modules $SERVICE/node_modules
RUN cp -r ../deps/node_modules node_modules
ADD services/$SERVICE/package.json /app-src/$SERVICE
ADD services/$SERVICE/package-lock.json /app-src/$SERVICE

WORKDIR $SERVICE

RUN npm install

ADD services/$SERVICE /app-src/$SERVICE
ADD services/lib /app-src/lib
