FROM screendriver_serverless

ARG SERVICE

WORKDIR ../app-src
RUN mkdir $SERVICE
ADD services/$SERVICE/package*.json /app-src/$SERVICE/

WORKDIR $SERVICE

RUN npm install

ADD services/$SERVICE /app-src/$SERVICE
ADD services/lib /app-src/lib

CMD echo ***DEPLOY OPTIONS***: region is $AWS_REGION, stage is $AWS_STAGE && \
    serverless deploy --verbose --region $AWS_REGION --stage $AWS_STAGE
