FROM screendriver_serverless AS deps

ARG SERVICE

ADD services/$SERVICE/package*.json ./

RUN npm install


FROM screendriver_serverless

ARG SERVICE

WORKDIR ../app-src

COPY --from=deps dynamodb/node_modules node_modules

WORKDIR $SERVICE

ADD services/$SERVICE /app-src/$SERVICE
ADD services/lib /app-src/lib
ADD scripts/run_tests.sh /app-src/$SERVICE

RUN ln -s ../lib ../node_modules/lib

CMD sh run_tests.sh
