FROM cdornbusch/docker-java-node:6.x

RUN npm install -g serverless@1.24.1

WORKDIR ../../dynamodb
ADD dynamodb/serverless.yml .
ADD dynamodb/package.json .

RUN cd $(npm root -g)/npm && \
    npm install fs-extra && \
    sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js

RUN npm install && serverless dynamodb install | grep -v "^$"
