FROM cdornbusch/docker-java-node:6.x

RUN npm install -g serverless@1.24.1 && \
    cd $(npm root -g)/npm && \
    npm install fs-extra && \
    sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js

WORKDIR ../../deps
ADD services/content-management-service/serverless.yml .
ADD services/content-management-service/serverless serverless
ADD services/content-management-service/package.json .
ADD services/content-management-service/package-lock.json .

RUN npm install && serverless dynamodb install --stage dev | grep -v "^$"
