FROM codeship/aws-deployment

RUN apk add --no-cache util-linux

CMD aws configure set region $AWS_REGION && \
    aws cognito-idp admin-create-user \
        --user-pool-id $USER_POOL_ID \
        --username $(uuidgen) \
        --user-attributes Name=email,Value=$FIRST_USER_EMAIL Name=custom:admin,Value=true Name=email_verified,Value=true
