Citizens Kitchen:
  Touch:
    A: http://touchscreen.citizenslasvegas.com/
    B: http://touchscreen.citizenslasvegas.com/
Hakkasan Las Vegas:
  Restaurant:
    A: http://touchscreen.hakkasan.com/
Searsucker Las Vegas:
  Touch:
    A: http://touchscreen.searsucker.com/
