ApiCreateUserResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    ParentId: ${self:custom.rootUrlId}
    PathPart: users
    RestApiId: ${self:custom.restApiId}

ApiCreateUserOptionsMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    MethodResponses: ${self:custom.optionsMethod.MethodResponses}
    Integration: ${self:custom.optionsMethod.Integration}
    ResourceId:
      Ref: ApiCreateUserResource
    RestApiId: ${self:custom.restApiId}

ApiCreateUserPostMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: POST
    ResourceId:
      Ref: ApiCreateUserResource
    RestApiId: ${self:custom.restApiId}
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri:
        Fn::Join:
          - ''
          - - ${self:custom.baseLambdaUri}
            - Fn::GetAtt:
              - CreateUnderscoreuserLambdaFunction
              - Arn
            - '/invocations'

CreateUserFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
      Fn::GetAtt:
        - CreateUnderscoreuserLambdaFunction
        - Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: ${self:custom.restApiArn}