ApiChangePasswordResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    ParentId: ${self:custom.rootUrlId}
    PathPart: change-password
    RestApiId: ${self:custom.restApiId}

ApiChangePasswordOptionsMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    MethodResponses: ${self:custom.optionsMethod.MethodResponses}
    Integration: ${self:custom.optionsMethod.Integration}
    ResourceId:
      Ref: ApiChangePasswordResource
    RestApiId: ${self:custom.restApiId}

ApiChangePasswordPostMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: POST
    ResourceId:
      Ref: ApiChangePasswordResource
    RestApiId: ${self:custom.restApiId}
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri:
        Fn::Join:
          - ''
          - - ${self:custom.baseLambdaUri}
            - Fn::GetAtt:
              - ChangeUnderscoreuserUnderscorepasswordLambdaFunction
              - Arn
            - '/invocations'

ChangeUserPasswordFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
      Fn::GetAtt:
        - ChangeUnderscoreuserUnderscorepasswordLambdaFunction
        - Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: ${self:custom.restApiArn}
