ApiSignOutResource:
  Type: AWS::ApiGateway::Resource
  Properties:
    ParentId: ${self:custom.rootUrlId}
    PathPart: sign_out
    RestApiId: ${self:custom.restApiId}

ApiSignOutOptionsMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: OPTIONS
    MethodResponses: ${self:custom.optionsMethod.MethodResponses}
    Integration: ${self:custom.optionsMethod.Integration}
    ResourceId:
      Ref: ApiSignOutResource
    RestApiId: ${self:custom.restApiId}

ApiSignOutPostMethod:
  Type: AWS::ApiGateway::Method
  Properties:
    AuthorizationType: NONE
    HttpMethod: POST
    ResourceId:
      Ref: ApiSignOutResource
    RestApiId: ${self:custom.restApiId}
    Integration:
      Type: AWS_PROXY
      IntegrationHttpMethod: POST
      Uri:
        Fn::Join:
          - ''
          - - ${self:custom.baseLambdaUri}
            - Fn::GetAtt:
              - SignUnderscoreoutLambdaFunction
              - Arn
            - '/invocations'

SignOutFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName:
      Fn::GetAtt:
        - SignUnderscoreoutLambdaFunction
        - Arn
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
    SourceArn: ${self:custom.restApiArn}