service: screen-driver-auth-api

frameworkVersion: ">=1.24.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage, 'dev'}
    REGION: ${opt:region, 'us-east-1'}
    USERS_TABLE: ${self:service}-users-${opt:stage}
    USER_POOL: ${self:service}-userpool-${opt:stage}
    USER_POOL_ID:
      Ref: CognitoUserPool
    USER_POOL_CLIENT: ${self:service}-appclient-${opt:stage}
    USER_POOL_CLIENT_ID:
      Ref: CognitoAppClient

  iamRoleStatements: ${self:custom.roles}

custom:
  cognitoResources: ${file(./serverless/cognito-resources.yml)}
  usersTableResource: ${file(./serverless/users-table-resource.yml)}
  functions: ${file(./serverless/functions.yml)}
  resources: ${file(./serverless/resources.yml)}
  outputs: ${file(./serverless/outputs.yml)}
  roles: ${file(./serverless/roles.yml)}
  authorizer: ${file(./serverless/authorizer.yml)}
  dynamodb:
    start:
      port: 8001
      inMemory: true
      migrate: true
    migration:
      dir: migrations
  serverless-offline:
    port: 3001

functions: ${self:custom.functions}

resources:
  Resources: ${self:custom.resources}
  Outputs: ${self:custom.outputs}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-mocha-plugin
  - serverless-export-env

package:
  include:
    - ../lib/**
  exclude:
    - serverless/**
    - test/**
    - .*
    - package*
