service: screen-driver-auth-api

frameworkVersion: ">=1.20.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage}
    USERS_TABLE: ${self:service}-users-${opt:stage}
    USER_POOL: ${self:service}-userpool-${opt:stage}
    USER_POOL_ID:
      Ref: CognitoUserPool
    USER_POOL_CLIENT: ${self:service}-appclient-${opt:stage}
    USER_POOL_CLIENT_ID:
      Ref: CognitoAppClient
  iamRoleStatements: ${self:custom.roles}

custom:
  cognitoResources: ${file(./serverless/cognito-resources.yml)}
  usersTableResource: ${file(./serverless/users-table-resource.yml)}
  functions: ${file(./serverless/functions.yml)}
  resources: ${file(./serverless/resources.yml)}
  outputs: ${file(./serverless/outputs.yml)}
  roles: ${file(./serverless/roles.yml)}

functions: ${self:custom.functions}

resources:
  Resources: ${self:custom.resources}
  Outputs: ${self:custom.outputs}

plugins:
  - serverless-offline
  - serverless-export-env

package:
  include:
    - ../lib/**
  exclude:
    - serverless
    - .*
    - package*
