service: screen-driver-auth-api

frameworkVersion: ">=1.24.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage, 'dev'}
    REGION: ${opt:region, 'us-east-1'}
    USERS_TABLE: ${self:service}-users-${opt:stage, 'dev'}
    USER_POOL_ID:
      Fn::ImportValue: ScreenDriverCognitoUserPoolId-${opt:stage, 'dev'}
    USER_POOL_CLIENT_ID:
      Fn::ImportValue: ScreenDriverCognitoAppClientId-${opt:stage, 'dev'}
  iamRoleStatements: ${self:custom.roles}

custom:
  usersTableResource: ${file(./serverless/users-table-resource.yml)}
  functions: ${file(./serverless/functions.yml)}
  resources: ${file(./serverless/resources.yml)}
  outputs: ${file(./serverless/outputs.yml)}
  roles: ${file(./serverless/roles.yml)}
  authorizer: ${file(./serverless/authorizer.yml)}
  dynamodb:
    start:
      port: 8001
      inMemory: true
      migrate: true
    migration:
      dir: migrations
  serverless-offline:
    port: 3001

functions: ${self:custom.functions}

resources:
  Resources: ${self:custom.resources}
  Outputs: ${self:custom.outputs}

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-mocha-plugin
  - serverless-export-env
  - serverless-plugin-browserifier

package:
  individually: true
  exclude:
    - serverless/**
    - test/**
    - .*
    - package*

    #exclude aws-sdk dependency as it exists in AWS Lambda runtime
    - node_modules/aws-sdk/**
    - node_modules/buffer/**
    - node_modules/crypto-browserify/**
    - node_modules/events/**
    - node_modules/jmespath/**
    - node_modules/querystring/**
    - node_modules/url/**
    - node_modules/sax/**
    - node_modules/xml2js/**
    - node_modules/xmlbuilder/**
