service: screen-driver-auth-api

frameworkVersion: ">=1.20.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage}
    USER_POOL: ${self:service}-userpool-${opt:stage}
    USER_POOL_ID:
      Ref: CognitoUserPool
    USER_POOL_CLIENT: ${self:service}-appclient-${opt:stage}
    USER_POOL_CLIENT_ID:
      Ref: CognitoAppClient
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource: arn:aws:cognito-idp:*

custom:
  optionsMethod: ${file(./serverless/options-method-properties.yml)}
  restApiArn: ${file(./serverless/rest-api-arn.yml)}
  baseLambdaUri: ${file(./serverless/base-lambda-uri.yml)}
  restApiId:
    Fn::ImportValue: ScreenDriverRestApi-${opt:stage}
  rootUrlId:
    Fn::ImportValue: ScreenDriverRootApiResource-${opt:stage}

functions:
  authenticate:
    handler: src/auth/authenticator.handler

  sign_out:
    handler: src/auth/sign_out.handler
    events:
      - http:
          path: api/sign_out
          method: post
          cors: true

  refresh_token:
    handler: src/auth_token/auth_token.refresh

resources:
  Resources:
    - ${file(serverless/cognito-resources.yml)}
    - ${file(serverless/api-resources-for-authenticate-function.yml)}
    - ${file(serverless/api-resources-for-refresh-token-function.yml)}

plugins:
  - serverless-offline
  - serverless-export-env

package:
  exclude:
    - .*
    - package*
