service: screen-driver-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage}
    CONTENT_TABLE: content
    VENUES_TABLE: venues
    CONFIGS_TABLE: configs
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*"

functions:
  get_venues_list:
    handler: venues/list.list
    events:
      - http:
          path: api/venues
          method: get
          cors: true

  create_venue:
    handler: venues/create.create
    events:
      - http:
          path: api/venues
          method: post
          cors: true

  update_venue:
    handler: venues/update.update
    events:
      - http:
          path: api/venues/{id}
          method: put
          cors: true

  delete_venue:
    handler: venues/delete.delete
    events:
      - http:
          path: api/venues/{id}
          method: delete
          cors: true

  get_content_list:
    handler: content/list.list
    events:
      - http:
          path: api/content
          method: get
          cors: true

  create_content:
    handler: content/create.create
    events:
      - http:
          path: api/content
          method: post
          cors: true

  update_content:
    handler: content/update.update
    events:
      - http:
          path: api/content/{id}
          method: put
          cors: true

  delete_content:
    handler: content/delete.delete
    events:
      - http:
          path: api/content/{id}
          method: delete
          cors: true

  get_settings_list:
    handler: setting/list.list
    events:
      - http:
          path: api/configs
          method: get
          cors: true

  create_setting:
    handler: setting/create.create
    events:
      - http:
          path: api/configs
          method: post
          cors: true

  update_setting:
    handler: setting/update.update
    events:
      - http:
          path: api/configs/{id}
          method: put
          cors: true

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: migrations

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-mocha-plugin

resources:
  Resources:
    ContentTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CONTENT_TABLE}

    VenuesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.VENUES_TABLE}

    ConfigsTable:
          Type: 'AWS::DynamoDB::Table'
          Properties:
            AttributeDefinitions:
              -
                AttributeName: id
                AttributeType: S
            KeySchema:
              -
                AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            TableName: ${self:provider.environment.CONFIGS_TABLE}
