service: screen-driver-api

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    STAGE: ${opt:stage}
    CONTENT_TABLE: content
    VENUES_TABLE: venues
    SETTINGS_TABLE: settings
  iamRoleStatements: ${self:custom.roles}

functions: ${self:custom.functions}

custom:
  properties: ${file(./serverless/properties.yml)}
  functions: ${file(./serverless/functions.yml)}
  resources: ${file(./serverless/resources.yml)}
  roles: ${file(./serverless/roles.yml)}
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: migrations

plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-mocha-plugin

resources:
  Resources: ${self:custom.resources}
